mqtt_client:
  ros__parameters:
    broker:
      host: 172.17.0.1
      port: 1883
    bridge:
    ros2mqtt:
      - ros_topic: /ping/ros
        mqtt_topic: pingpong/ros
      - ros_topic: /ping/primitive
        mqtt_topic: pingpong/primitive
        primitive: true
    mqtt2ros:
      - mqtt_topic: pingpong/ros
        ros_topic: /pong/ros
      - mqtt_topic: pingpong/primitive
        ros_topic: /pong/primitive
        primitive: true
