mqtt_client:
  ros__parameters:
    broker:
      host: 172.17.0.1
      port: 1883
    bridge:
      ros2mqtt:                     # Object specifying which ROS topics to map to which MQTT topics
        ros_topics:                 # Array specifying which ROS topics to bridge
          - /goalPosition/tomqtt               # The ROS topic that should be bridged, corresponds to the sub-object in the YAML
          - /currentPosition/tomqtt
        /goalPosition/tomqtt:  
          mqtt_topic: goalPosition/tomqtt  # MQTT topic on which the corresponding ROS messages are sent to the broker
          primitive: true
        /currentPosition/tomqtt:
          mqtt_topic: currentPosition/tomqtt
          primitive: true
      mqtt2ros:                     # Object specifying which MQTT topics to map to which ROS topics
        mqtt_topics:                # Array specifying which ROS topics to bridge
          - goalPosition/tomqtt           # The MQTT topic that should be bridged, corresponds to the sub-object in the YAML
          - currentPosition/tomqtt
        goalPosition/tomqtt:
          ros_topic: /goalPositionPong/tomqtt     # ROS topic on which corresponding MQTT messages are published
          primitive: true
        currentPosition/tomqtt:
          ros_topic: /currentPositionPong/tomqtt     # ROS topic on which corresponding MQTT messages are published
          primitive: true
